### ISSUE TITLE
Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly

### ISSUE THREAD

**Issue by hjspencer** [varun-raj/immich-power-tools#11]
Using the latest power tools (v0.1.6) within the immich dockerfile I don't get any images on the Manage People & Potential Albums tabs
When I load Power Tools I get the following error in the docker logs

```
immich_power_tools       | 0
immich_power_tools       |  ⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
```

**Comment by varun-raj** [comment]
Look like this is happening for image optimization. I will check on it

**Comment by varun-raj** [comment]
Hi @hjspencer,

I've fixed this in the latest docker build, can you please try it and let me know?

**Comment by hjspencer** [comment]
I now get an error 

Request failed with status code 500

Here is the log

`immich_power_tools       |   ▲ Next.js 14.2.5
immich_power_tools       |   - Local:        http://84cdf54502e9:3000
immich_power_tools       |   - Network:      http://172.29.12.3:3000
immich_power_tools       | 
immich_power_tools       |  ✓ Starting...
immich_power_tools       |  ✓ Ready in 188ms
immich_power_tools       | error: terminating connection due to administrator command
immich_power_tools       |     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_power_tools       |     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_power_tools       |     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_power_tools       |     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_power_tools       |     at Socket.emit (node:events:517:28)
immich_power_tools       |     at addChunk (node:internal/streams/readable:368:12)
immich_power_tools       |     at readableAddChunk (node:internal/streams/readable:341:9)
immich_power_tools       |     at Readable.push (node:internal/streams/readable:278:10)
immich_power_tools       |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
immich_power_tools       |   length: 116,
immich_power_tools       |   severity: 'FATAL',
immich_power_tools       |   code: '57P01',
immich_power_tools       |   detail: undefined,
immich_power_tools       |   hint: undefined,
immich_power_tools       |   position: undefined,
immich_power_tools       |   internalPosition: undefined,
immich_power_tools       |   internalQuery: undefined,
immich_power_tools       |   where: undefined,
immich_power_tools       |   schema: undefined,
immich_power_tools       |   table: undefined,
immich_power_tools       |   column: undefined,
immich_power_tools       |   dataType: undefined,
immich_power_tools       |   constraint: undefined,
immich_power_tools       |   file: 'postgres.c',
immich_power_tools       |   line: '3204',
immich_power_tools       |   routine: 'ProcessInterrupts'
immich_power_tools       | }
immich_power_tools       | Error: Connection terminated unexpectedly
immich_power_tools       |     at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:132:73)
immich_power_tools       |     at Object.onceWrapper (node:events:631:28)
immich_power_tools       |     at Connection.emit (node:events:517:28)
immich_power_tools       |     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:63:12)
immich_power_tools       |     at Socket.emit (node:events:517:28)
immich_power_tools       |     at TCP.<anonymous> (node:net:350:12)
immich_power_tools       |   ▲ Next.js 14.2.5
immich_power_tools       |   - Local:        http://84cdf54502e9:3000
immich_power_tools       |   - Network:      http://172.29.12.3:3000
immich_power_tools       | 
immich_power_tools       |  ✓ Starting...
immich_power_tools       |  ✓ Ready in 397ms
immich_power_tools       |   ▲ Next.js 14.2.5
immich_power_tools       |   - Local:        http://84cdf54502e9:3000
immich_power_tools       |   - Network:      http://172.29.12.3:3000
immich_power_tools       | 
immich_power_tools       |  ✓ Starting...
immich_power_tools       |  ✓ Ready in 348ms`

**Comment by varun-raj** [comment]
@hjspencer, Looks like some issue with the DB Connection, can you please share your `.env` if possible?
